### PR TITLE
Docker dev environment for the app

### PR DESCRIPTION
**Pull request by papajulio**
Dev environment for docker, it allow you to launch the app without installing nothing (except docker) and with only one command. 

Using the script launch-docker-env.sh it launches two containers. On for the postgre database and another for the Rails app. The app it's accessible in http://localhost:3000/ and can be worked directly in the code in the host machine as I had mounted with a volume.

The reason behind this is that I wanted to start collaborating so I needed and environment and I didn't want to install another database and Ruby and Rails in my computer directly. Hopefully this will help others too as allows you to bootstrap the app very easily.

Let me know if you need some improvements or modifications.

How to use docker in Mac: https://docs.docker.com/installation/mac/
How to use docker in Windows: https://docs.docker.com/installation/windows/

### CODE REVIEW

**Comment by dcabo** [comment]
Hi, thanks for the pull request. I'm having some issues running the script, maybe caused by the fact I'm new to Docker.

First, I get an error on the `sed` command:

 > sed: 1: "config/database.yml": command c expects \ followed by text

And after I've run the script once I cannot try again, because I get an error along the lines of:

> FATA[0000] Error response from daemon: Conflict. The name "quienmanda-db" is already in use by container 26c732500cf2. You have to delete (or rename) that container to be able to reuse that name. 
neko:quienmanda.es(papajulio-docker-env)

See [this gist](https://gist.github.com/dcabo/4f91c6247c7ce1fb8a4b) for the full output. I have to go and do `docker rm 26c732500cf2` before I can run it again. Is this normal?

**Comment by papajulio** [comment]
I will take a look to the sed issue I guess it's a problem with compatibility between Mac sed and Linux one. Or you are running the script in another linux distro? (I use Ubuntu)

I will add some documentation on how to use the script and a clean command to remove the containers when you finish your work or get errors.

**Comment by dcabo** [comment]
Hi, about the sed issue, this worked for me (in OS X):

    sed -i '' 's/*default/*docker/g' config/database.yml

In OS X (don't know about other operating systems) the `-i` option expects an argument, which is the extension to use for the backup file.

Thanks

**Comment by papajulio** [comment]
Hello, I've fixed the issue with sed so it runs ok in both Linux and OSX. I had improved the script so it doesn't try to launch the db container again if you run it twice in a row. And I have added a section to INSTALL.md with some instructions.

Let me know how do you see it now.

**Comment by dcabo** [comment]
It's now merged, thanks @papajulio

**Comment by jrub** [comment]
:clap: :clap: :clap:

**Pull request merged**
